"""Initial migration: create all tables

Revision ID: 1de788be43fc
Revises: 
Create Date: 2026-03-07 19:44:37.958412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1de788be43fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dias_id'), 'dias', ['id'], unique=False)
    op.create_table('emisoras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('urlStream', sa.String(length=500), nullable=False),
    sa.Column('urlImagen', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emisoras_id'), 'emisoras', ['id'], unique=False)
    op.create_table('noticias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titular', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_noticias_id'), 'noticias', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('hermandades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('idDia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idDia'], ['dias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hermandades_id'), 'hermandades', ['id'], unique=False)
    op.create_table('itinerarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idUsuario')
    )
    op.create_index(op.f('ix_itinerarios_id'), 'itinerarios', ['id'], unique=False)
    op.create_table('infopaso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('tipoPaso', sa.Enum('CRUZGUIA', 'PALIO', 'DUELO', 'PASO', name='tipopaso'), nullable=False),
    sa.Column('localizacion', sa.String(length=255), nullable=False),
    sa.Column('idHermandad', sa.Integer(), nullable=False),
    sa.Column('difHora', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['idHermandad'], ['hermandades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infopaso_id'), 'infopaso', ['id'], unique=False)
    op.create_table('items_itinerario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idItinerario', sa.Integer(), nullable=False),
    sa.Column('idInfoPaso', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idInfoPaso'], ['infopaso.id'], ),
    sa.ForeignKeyConstraint(['idItinerario'], ['itinerarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idItinerario', 'idInfoPaso', name='uq_itinerario_infopaso')
    )
    op.create_index(op.f('ix_items_itinerario_id'), 'items_itinerario', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_itinerario_id'), table_name='items_itinerario')
    op.drop_table('items_itinerario')
    op.drop_index(op.f('ix_infopaso_id'), table_name='infopaso')
    op.drop_table('infopaso')
    op.drop_index(op.f('ix_itinerarios_id'), table_name='itinerarios')
    op.drop_table('itinerarios')
    op.drop_index(op.f('ix_hermandades_id'), table_name='hermandades')
    op.drop_table('hermandades')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_noticias_id'), table_name='noticias')
    op.drop_table('noticias')
    op.drop_index(op.f('ix_emisoras_id'), table_name='emisoras')
    op.drop_table('emisoras')
    op.drop_index(op.f('ix_dias_id'), table_name='dias')
    op.drop_table('dias')
    # ### end Alembic commands ###
