"""updated_noticias_contenido

Revision ID: 1e466fcc1d03
Revises: d0b556751b4e
Create Date: 2026-07-05 21:36:09.123291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1e466fcc1d03'
down_revision: Union[str, Sequence[str], None] = 'd0b556751b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noticias', sa.Column('contenido', sa.Text(), nullable=False))
    op.add_column('noticias', sa.Column('url_imagen', sa.String(length=500), nullable=False))
    op.add_column('noticias', sa.Column('origen', sa.String(length=50), nullable=False))
    op.drop_column('noticias', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noticias', sa.Column('url', mysql.VARCHAR(length=500), nullable=False))
    op.drop_column('noticias', 'origen')
    op.drop_column('noticias', 'url_imagen')
    op.drop_column('noticias', 'contenido')
    # ### end Alembic commands ###
