"""Added new ENUM types for TipoPaso

Revision ID: 3ee1c0b5b9cd
Revises: 7ee3bfe4c660
Create Date: 2026-02-22 21:18:13.309976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ee1c0b5b9cd'
down_revision: Union[str, Sequence[str], None] = '7ee3bfe4c660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('infopaso', 'tipoPaso',
               existing_type=sa.String(),
               type_=sa.Enum('CruzGuia', 'Palio', 'Duelo', 'Paso', name='tipopaso'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('infopaso', 'tipoPaso',
               existing_type=sa.Enum('CruzGuia', 'Palio', 'Duelo', 'Paso', name='tipopaso'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###
