"""Fixed relationship names

Revision ID: 5eea62a39cd9
Revises: 8919fbe70fe1
Create Date: 2026-02-22 12:57:28.918183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5eea62a39cd9'
down_revision: Union[str, Sequence[str], None] = '8919fbe70fe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hermandades', sa.Column('idDia', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('hermandades_ibfk_1'), 'hermandades', type_='foreignkey')
    op.create_foreign_key(None, 'hermandades', 'dias', ['idDia'], ['id'])
    op.drop_column('hermandades', 'dia')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hermandades', sa.Column('dia', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'hermandades', type_='foreignkey')
    op.create_foreign_key(op.f('hermandades_ibfk_1'), 'hermandades', 'dias', ['dia'], ['id'])
    op.drop_column('hermandades', 'idDia')
    # ### end Alembic commands ###
