"""Added new ENUM types for TipoPaso

Revision ID: 7ee3bfe4c660
Revises: d60d19878b55
Create Date: 2026-02-22 21:14:13.256438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ee3bfe4c660'
down_revision: Union[str, Sequence[str], None] = 'd60d19878b55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
