"""Added Dia to the models

Revision ID: 8919fbe70fe1
Revises: d7f5145ec348
Create Date: 2026-02-22 12:08:33.564877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8919fbe70fe1'
down_revision: Union[str, Sequence[str], None] = 'd7f5145ec348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dias_id'), 'dias', ['id'], unique=False)
    op.alter_column('hermandades', 'dia',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_foreign_key(None, 'hermandades', 'dias', ['dia'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hermandades', type_='foreignkey')
    op.alter_column('hermandades', 'dia',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_dias_id'), table_name='dias')
    op.drop_table('dias')
    # ### end Alembic commands ###
