"""Recrear tabla items_itinerario

Revision ID: bfa6874098ec
Revises: af818172b989
Create Date: 2026-04-25 20:11:47.640776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfa6874098ec'
down_revision: Union[str, Sequence[str], None] = 'af818172b989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items_itinerario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idItinerario', sa.Integer(), nullable=False),
    sa.Column('idInfoPaso', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idInfoPaso'], ['infopaso.id'], ),
    sa.ForeignKeyConstraint(['idItinerario'], ['itinerarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idItinerario', 'idInfoPaso', name='uq_itinerario_infopaso')
    )
    op.create_index(op.f('ix_items_itinerario_id'), 'items_itinerario', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_itinerario_id'), table_name='items_itinerario')
    op.drop_table('items_itinerario')
    # ### end Alembic commands ###
