"""add esCarreraOficial to infopaso

Revision ID: d0b556751b4e
Revises: 9888336fc795
Create Date: 2026-06-08 20:37:02.654286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0b556751b4e'
down_revision: Union[str, Sequence[str], None] = '9888336fc795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('infopaso', sa.Column('esCarreraOficial', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('infopaso', 'esCarreraOficial')
    # ### end Alembic commands ###
