"""difHora is now optional and nullable

Revision ID: d60d19878b55
Revises: 5eea62a39cd9
Create Date: 2026-02-22 13:00:29.331401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd60d19878b55'
down_revision: Union[str, Sequence[str], None] = '5eea62a39cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('infopaso', 'difHora',
               existing_type=mysql.TIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('infopaso', 'difHora',
               existing_type=mysql.TIME(),
               nullable=False)
    # ### end Alembic commands ###
