"""Initial migration: create all tables

Revision ID: d7f5145ec348
Revises: 
Create Date: 2026-02-22 11:56:22.054176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd7f5145ec348'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('infopaso', sa.Column('difHora', sa.Time(), nullable=False))
    op.alter_column('infopaso', 'hora',
               existing_type=mysql.INTEGER(),
               type_=sa.Time(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('infopaso', 'hora',
               existing_type=sa.Time(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.drop_column('infopaso', 'difHora')
    # ### end Alembic commands ###
