"""Initial migration: create all tables

Revision ID: d7f5145ec348
Revises: 
Create Date: 2026-02-22 11:56:22.054176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = 'd7f5145ec348'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(table_name: str, column_name: str) -> bool:
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade() -> None:
    """Upgrade schema."""
    # Crear la tabla `infopaso` si no existe
    op.create_table(
        'infopaso',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('nombre', sa.String(length=255), nullable=False),
        sa.Column('hora', sa.Time(), nullable=False),
        sa.Column('difHora', sa.Time(), nullable=True),
    )

    # Modificar columnas existentes
    if not column_exists('infopaso', 'difHora'):
        op.add_column('infopaso', sa.Column('difHora', sa.Time(), nullable=False))
    op.alter_column('infopaso', 'hora',
               existing_type=mysql.INTEGER(),
               type_=sa.Time(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('infopaso', 'hora',
               existing_type=sa.Time(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.drop_column('infopaso', 'difHora')
    # ### end Alembic commands ###
